"""add description and type to settlements

Revision ID: 18426b2571f3
Revises: cb2f7b5ebcec
Create Date: 2026-03-19 15:33:39.965463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18426b2571f3'
down_revision: Union[str, None] = 'cb2f7b5ebcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settlements', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('settlements', sa.Column('type', sa.String(length=20), nullable=True))
    op.execute("UPDATE settlements SET type = 'settle_up' WHERE type IS NULL")
    op.alter_column('settlements', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'type')
    op.drop_column('settlements', 'description')
    # ### end Alembic commands ###
