"""add nicknames to group_members

Revision ID: 1bc6c9ed9cc8
Revises: 28d2ebd94e16
Create Date: 2026-04-04 14:52:11.186405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc6c9ed9cc8'
down_revision: Union[str, None] = '28d2ebd94e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('nicknames', sa.String(length=500), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'nicknames')
    # ### end Alembic commands ###
