"""add bank_bin to payment_methods

Revision ID: 6d25a9d6edc8
Revises: 9721d86e63d2
Create Date: 2026-03-23 16:54:25.080989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d25a9d6edc8'
down_revision: Union[str, None] = '9721d86e63d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('bank_bin', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'bank_bin')
    # ### end Alembic commands ###
