"""add exchange_rate and converted_amount to expenses

Revision ID: bbd591bdf0ad
Revises: 4fba9a9b1c0b
Create Date: 2026-03-19 00:04:23.108365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd591bdf0ad'
down_revision: Union[str, None] = '4fba9a9b1c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('expenses', sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True))
    op.add_column('expenses', sa.Column('converted_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # Backfill existing rows: exchange_rate=1, converted_amount=amount
    op.execute("UPDATE expenses SET exchange_rate = 1 WHERE exchange_rate IS NULL")
    op.execute("UPDATE expenses SET converted_amount = amount WHERE converted_amount IS NULL")
    # Make non-nullable
    op.alter_column('expenses', 'exchange_rate', nullable=False)
    op.alter_column('expenses', 'converted_amount', nullable=False)
    op.create_foreign_key('fk_groups_default_category', 'groups', 'categories', ['default_category_id'], ['id'], ondelete='SET NULL', use_alter=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_groups_default_category', 'groups', type_='foreignkey')
    op.drop_column('expenses', 'converted_amount')
    op.drop_column('expenses', 'exchange_rate')
    # ### end Alembic commands ###
